[project]
name = "zalfmas-capnp-schemas"
version = "0.1.37"
description = ""
readme = "README.md"
requires-python = ">=3.10,<4.0"
authors = [{ name = "Michael Berg-Mohnicke", email = "michael.berg@zalf.de" }]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
